/**
 * Cross-Tool Context Sync Routes
 * Export stored knowledge as .cursorrules, CLAUDE.md, or AGENTS.md.
 * Single source of truth for multi-editor context synchronization.
 */

import { Hono } from "hono";
import { getDb, MemorySearch } from "@exocortex/core";

const app = new Hono();

/**
 * GET /api/context/export?format=cursorrules|claude|agents&namespace=&tags=
 *
 * Generates context files from stored memories.
 */
app.get("/api/context/export", async (c) => {
  const format = c.req.query("format") || "claude";
  const namespace = c.req.query("namespace");
  const tagsParam = c.req.query("tags");
  const tags = tagsParam ? tagsParam.split(",").map(t => t.trim()) : undefined;
  const limit = parseInt(c.req.query("limit") || "30", 10);

  const db = getDb();
  const search = new MemorySearch(db);

  // Fetch relevant memories — prefer semantic/procedural tier, high importance
  const results = await search.search({
    query: namespace ? `${namespace} project context conventions patterns` : "project context conventions architecture",
    limit,
    namespace,
    tags,
    active_only: true,
  });

  if (results.length === 0) {
    return c.text("No memories found for context generation.", 404);
  }

  // Group memories by type
  const decisions: string[] = [];
  const conventions: string[] = [];
  const architecture: string[] = [];
  const techniques: string[] = [];
  const other: string[] = [];

  for (const r of results) {
    const memTags = r.memory.tags || [];
    const content = r.memory.content.trim();
    const preview = content.length > 500 ? content.slice(0, 500) + "..." : content;

    if (memTags.includes("decision") || memTags.includes("architecture")) {
      architecture.push(preview);
    } else if (memTags.includes("technique") || memTags.includes("learning") || r.memory.tier === "procedural") {
      techniques.push(preview);
    } else if (memTags.includes("convention") || memTags.includes("style") || memTags.includes("pattern")) {
      conventions.push(preview);
    } else if (r.memory.tier === "semantic") {
      decisions.push(preview);
    } else {
      other.push(preview);
    }
  }

  switch (format) {
    case "cursorrules":
      return c.text(generateCursorrules(namespace, architecture, conventions, techniques));

    case "agents":
    case "agents.md":
      return c.text(generateAgentsMd(namespace, architecture, conventions, techniques, decisions));

    case "claude":
    case "claude.md":
    default:
      return c.text(generateClaudeMd(namespace, architecture, conventions, techniques, decisions));
  }
});

function generateClaudeMd(
  namespace: string | undefined,
  architecture: string[],
  conventions: string[],
  techniques: string[],
  decisions: string[],
): string {
  const lines: string[] = [];
  const name = namespace || "Project";

  lines.push(`# ${name} — Context (auto-generated by Exocortex)\n`);

  if (architecture.length) {
    lines.push("## Architecture & Decisions\n");
    for (const a of architecture) lines.push(`- ${a}\n`);
  }

  if (conventions.length) {
    lines.push("\n## Conventions\n");
    for (const c of conventions) lines.push(`- ${c}\n`);
  }

  if (techniques.length) {
    lines.push("\n## Techniques & Patterns\n");
    for (const t of techniques) lines.push(`- ${t}\n`);
  }

  if (decisions.length) {
    lines.push("\n## Key Facts\n");
    for (const d of decisions) lines.push(`- ${d}\n`);
  }

  lines.push(`\n---\n*Generated from Exocortex memory on ${new Date().toISOString().split("T")[0]}*\n`);
  return lines.join("");
}

function generateCursorrules(
  namespace: string | undefined,
  architecture: string[],
  conventions: string[],
  techniques: string[],
): string {
  const lines: string[] = [];
  const name = namespace || "Project";

  lines.push(`# ${name} Rules (auto-generated by Exocortex)\n\n`);

  if (architecture.length) {
    lines.push("## Architecture\n");
    for (const a of architecture.slice(0, 10)) lines.push(`- ${a}\n`);
  }

  if (conventions.length) {
    lines.push("\n## Conventions\n");
    for (const c of conventions.slice(0, 10)) lines.push(`- ${c}\n`);
  }

  if (techniques.length) {
    lines.push("\n## Patterns\n");
    for (const t of techniques.slice(0, 10)) lines.push(`- ${t}\n`);
  }

  return lines.join("");
}

function generateAgentsMd(
  namespace: string | undefined,
  architecture: string[],
  conventions: string[],
  techniques: string[],
  decisions: string[],
): string {
  const lines: string[] = [];
  const name = namespace || "Project";

  lines.push(`# ${name} Agent Context\n\n`);
  lines.push(`This file is auto-generated from Exocortex memory. It provides context for AI agents working on this project.\n\n`);

  if (architecture.length) {
    lines.push("## Key Architecture Decisions\n");
    for (const a of architecture) lines.push(`- ${a}\n`);
  }

  if (conventions.length) {
    lines.push("\n## Coding Conventions\n");
    for (const c of conventions) lines.push(`- ${c}\n`);
  }

  if (techniques.length) {
    lines.push("\n## Learned Techniques\n");
    for (const t of techniques) lines.push(`- ${t}\n`);
  }

  if (decisions.length) {
    lines.push("\n## Project Facts\n");
    for (const d of decisions) lines.push(`- ${d}\n`);
  }

  return lines.join("");
}

export default app;
